#!/bin/bash

# --- Path configuration ---
DOTFILES_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
HOME_DIR=$HOME

if command -v cygpath >/dev/null 2>&1; then
    VSCODE_USER_DIR="$(cygpath "$APPDATA")/Code/User"
else
    VSCODE_USER_DIR="/c/Users/$USER/AppData/Roaming/Code/User"
fi

echo "🚀 Installing dotfiles..."

# --- 0. Local configuration (env.local) ---
# Bootstrap personal config from the versioned template.
ENV_EXAMPLE="$DOTFILES_DIR/git-bash/env.example"
ENV_LOCAL="$DOTFILES_DIR/git-bash/env.local"
if [ ! -f "$ENV_LOCAL" ] && [ -f "$ENV_EXAMPLE" ]; then
    cp "$ENV_EXAMPLE" "$ENV_LOCAL"
    echo "📄 Created git-bash/env.local from template — edit your paths and re-run."
fi
[ -f "$ENV_LOCAL" ] && source "$ENV_LOCAL"

# --- 1. Git Bash loader ---
echo "📝 Configuring Git Bash loader..."

BASHRC="$HOME_DIR/.bashrc"
MARKER="# dotfiles-loader"

# Back up an existing, non-generated .bashrc once (never clobber a prior backup).
if [ -f "$BASHRC" ] && ! grep -q "$MARKER" "$BASHRC" && [ ! -f "$BASHRC.bak" ]; then
    cp "$BASHRC" "$BASHRC.bak"
    echo "📦 Backed up existing .bashrc to .bashrc.bak"
fi

cat << EOF > "$BASHRC"
$MARKER
# Auto-generated by the dotfiles install script
if [ -f "$DOTFILES_DIR/git-bash/.bashrc" ]; then
    source "$DOTFILES_DIR/git-bash/.bashrc"
fi
EOF

echo "✅ .bashrc loader created."

# --- 2. Generate VS Code workspace ---
# .code-workspace JSON can't expand env vars, so render it from the template.
WS_TEMPLATE="$DOTFILES_DIR/vscode/workspaces/sfcc.code-workspace.template"
WS_OUTPUT="$DOTFILES_DIR/vscode/workspaces/sfcc.code-workspace"
if [ -f "$WS_TEMPLATE" ]; then
    : ${SFCC_PROJECT_NAME:="📦 SFCC Project"}
    : ${SFCC_PROJECT_DIR:="../../../CHANGE_ME"}
    # Replace a literal token with a literal value (pure prefix/suffix ops —
    # no sed/regex, so & | \ in the value can never corrupt the output).
    subst() {
        local hay=$1 tok=$2 rep=$3 out=""
        while [ "$hay" != "${hay#*"$tok"}" ]; do
            out=$out${hay%%"$tok"*}$rep
            hay=${hay#*"$tok"}
        done
        printf '%s' "$out$hay"
    }
    # Escape double-quotes so the values stay valid JSON strings (paths use
    # forward slashes, so no backslash escaping is needed).
    name=$(subst "$SFCC_PROJECT_NAME" '"' '\"')
    dir=$(subst "$SFCC_PROJECT_DIR" '"' '\"')
    ws=$(cat "$WS_TEMPLATE")
    ws=$(subst "$ws" '${SFCC_PROJECT_NAME}' "$name")
    ws=$(subst "$ws" '${SFCC_PROJECT_DIR}' "$dir")
    printf '%s\n' "$ws" > "$WS_OUTPUT"
    echo "🧩 Generated workspace: vscode/workspaces/sfcc.code-workspace"
fi

# --- 3. Link VS Code config ---
link_vscode() {
    local src="$1"
    local dest="$2"
    # Back up a real (non-symlink) target once before replacing it.
    if [ -e "$dest" ] && [ ! -L "$dest" ] && [ ! -e "$dest.bak" ]; then
        mv "$dest" "$dest.bak"
        echo "📦 Backed up $(basename "$dest") to $(basename "$dest").bak"
    fi
    # Drop any leftover (e.g. a symlink from a previous run).
    [ -e "$dest" ] && rm -rf "$dest"
    echo "🔗 Linking VS Code: $(basename "$dest")"
    export MSYS_WINSYM_LINKS=1
    ln -s "$src" "$dest"
}

if [ -d "$VSCODE_USER_DIR" ]; then
    [ -f "$DOTFILES_DIR/vscode/settings.json" ] && link_vscode "$DOTFILES_DIR/vscode/settings.json" "$VSCODE_USER_DIR/settings.json"
    [ -d "$DOTFILES_DIR/vscode/snippets" ] && link_vscode "$DOTFILES_DIR/vscode/snippets" "$VSCODE_USER_DIR/snippets"
else
    echo "⚠️  VS Code user directory not found. Skipping links."
fi

echo "✨ Done! Restart Git Bash."
