#!/bin/bash

# --- Path configuration ---
DOTFILES_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
HOME_DIR=$HOME

if command -v cygpath >/dev/null 2>&1; then
    APPDATA_DIR="$(cygpath "$APPDATA")"
else
    APPDATA_DIR="/c/Users/$USER/AppData/Roaming"
fi
VSCODE_USER_DIR="$APPDATA_DIR/Code/User"
ZED_USER_DIR="$APPDATA_DIR/Zed"

echo "🚀 Installing dotfiles..."

# --- 0. Local configuration (env.local) ---
# Bootstrap personal config from the versioned template.
ENV_EXAMPLE="$DOTFILES_DIR/git-bash/env.example"
ENV_LOCAL="$DOTFILES_DIR/git-bash/env.local"
if [ ! -f "$ENV_LOCAL" ] && [ -f "$ENV_EXAMPLE" ]; then
    cp "$ENV_EXAMPLE" "$ENV_LOCAL"
    echo "📄 Created git-bash/env.local from template — edit your paths and re-run."
fi
[ -f "$ENV_LOCAL" ] && source "$ENV_LOCAL"

# --- 1. Interactive choices ---
# Answers live in env.local, so a re-run defaults to the previous choice and a
# non-interactive run keeps it.

ask() {
    local prompt=$1 default=$2 reply=""
    if ! read -r -p "$prompt" reply; then
        reply=""
        # Probe /dev/tty quietly: it doesn't exist in every environment.
        if [ ! -t 0 ] && { : < /dev/tty; } 2>/dev/null; then
            read -r -p "$prompt" reply < /dev/tty || reply=""
        fi
    fi
    printf '%s' "${reply:-$default}"
}

# Upsert `export KEY="value"` in env.local without touching the other lines.
set_env_var() {
    local key=$1 value=$2 tmp="$ENV_LOCAL.tmp" line
    : > "$tmp"
    if [ -f "$ENV_LOCAL" ]; then
        while IFS= read -r line || [ -n "$line" ]; do
            case $line in
                "export $key="*|"$key="*) ;;
                *) printf '%s\n' "$line" >> "$tmp" ;;
            esac
        done < "$ENV_LOCAL"
    fi
    printf 'export %s="%s"\n' "$key" "$value" >> "$tmp"
    mv "$tmp" "$ENV_LOCAL"
}

: ${DOTFILES_CUSTOM_PROMPT:="yes"}
answer=$(ask "❓ Use the custom Git Bash prompt (git-prompt.sh)? [yes/no] ($DOTFILES_CUSTOM_PROMPT): " "$DOTFILES_CUSTOM_PROMPT")
case $(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]') in
    y|yes|s|si|sí) DOTFILES_CUSTOM_PROMPT="yes" ;;
    n|no)          DOTFILES_CUSTOM_PROMPT="no" ;;
esac
set_env_var DOTFILES_CUSTOM_PROMPT "$DOTFILES_CUSTOM_PROMPT"
if [ "$DOTFILES_CUSTOM_PROMPT" = "yes" ]; then
    echo "🎨 Custom prompt enabled."
else
    echo "🎨 Custom prompt skipped (Git Bash keeps its default prompt)."
fi

: ${DOTFILES_EDITOR:="code"}
answer=$(ask "❓ Favourite code editor? [1] VS Code  [2] Zed ($DOTFILES_EDITOR): " "$DOTFILES_EDITOR")
case $(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]') in
    1|code|vscode|"vs code") DOTFILES_EDITOR="code" ;;
    2|zed)                   DOTFILES_EDITOR="zed" ;;
esac
set_env_var DOTFILES_EDITOR "$DOTFILES_EDITOR"
echo "🧑‍💻 Editor: $DOTFILES_EDITOR"

# --- 2. Git Bash loader ---
echo "📝 Configuring Git Bash loader..."

BASHRC="$HOME_DIR/.bashrc"
MARKER="# dotfiles-loader"

# Back up an existing, non-generated .bashrc once (never clobber a prior backup).
if [ -f "$BASHRC" ] && ! grep -q "$MARKER" "$BASHRC" && [ ! -f "$BASHRC.bak" ]; then
    cp "$BASHRC" "$BASHRC.bak"
    echo "📦 Backed up existing .bashrc to .bashrc.bak"
fi

cat << EOF > "$BASHRC"
$MARKER
# Auto-generated by the dotfiles install script
if [ -f "$DOTFILES_DIR/git-bash/.bashrc" ]; then
    source "$DOTFILES_DIR/git-bash/.bashrc"
fi
EOF

echo "✅ .bashrc loader created."

# --- 3. Generate VS Code workspace ---
# .code-workspace JSON can't expand env vars, so render it from the template.
WS_TEMPLATE="$DOTFILES_DIR/vscode/workspaces/sfcc.code-workspace.template"
WS_OUTPUT="$DOTFILES_DIR/vscode/workspaces/sfcc.code-workspace"
if [ -f "$WS_TEMPLATE" ]; then
    : ${SFCC_PROJECT_NAME:="📦 SFCC Project"}
    : ${SFCC_PROJECT_DIR:="../../../CHANGE_ME"}
    : ${PLAYWRIGHT_PROJECT_NAME:="🎭 Playwright Tests"}
    : ${PLAYWRIGHT_PROJECT_DIR:="../../../sfcc-playwright-test"}
    # Replace a literal token with a literal value (pure prefix/suffix ops —
    # no sed/regex, so & | \ in the value can never corrupt the output).
    subst() {
        local hay=$1 tok=$2 rep=$3 out=""
        while [ "$hay" != "${hay#*"$tok"}" ]; do
            out=$out${hay%%"$tok"*}$rep
            hay=${hay#*"$tok"}
        done
        printf '%s' "$out$hay"
    }
    # Escape double-quotes so the values stay valid JSON strings (paths use
    # forward slashes, so no backslash escaping is needed).
    name=$(subst "$SFCC_PROJECT_NAME" '"' '\"')
    dir=$(subst "$SFCC_PROJECT_DIR" '"' '\"')
    pwname=$(subst "$PLAYWRIGHT_PROJECT_NAME" '"' '\"')
    pwdir=$(subst "$PLAYWRIGHT_PROJECT_DIR" '"' '\"')
    ws=$(cat "$WS_TEMPLATE")
    ws=$(subst "$ws" '${SFCC_PROJECT_NAME}' "$name")
    ws=$(subst "$ws" '${SFCC_PROJECT_DIR}' "$dir")
    ws=$(subst "$ws" '${PLAYWRIGHT_PROJECT_NAME}' "$pwname")
    ws=$(subst "$ws" '${PLAYWRIGHT_PROJECT_DIR}' "$pwdir")
    printf '%s\n' "$ws" > "$WS_OUTPUT"
    echo "🧩 Generated workspace: vscode/workspaces/sfcc.code-workspace"
fi

# --- 4. Link editor config ---
link_editor() {
    local src="$1"
    local dest="$2"
    # Back up a real (non-symlink) target once before replacing it.
    if [ -e "$dest" ] && [ ! -L "$dest" ] && [ ! -e "$dest.bak" ]; then
        mv "$dest" "$dest.bak"
        echo "📦 Backed up $(basename "$dest") to $(basename "$dest").bak"
    fi
    # Drop any leftover (e.g. a symlink from a previous run).
    [ -e "$dest" ] && rm -rf "$dest"
    echo "🔗 Linking: $(basename "$dest")"
    export MSYS_WINSYM_LINKS=1
    ln -s "$src" "$dest"
}

if [ "$DOTFILES_EDITOR" = "zed" ]; then
    # Zed may not have run yet, so create its config directory if needed.
    mkdir -p "$ZED_USER_DIR"
    if [ -d "$DOTFILES_DIR/zed" ]; then
        [ -f "$DOTFILES_DIR/zed/settings.json" ] && link_editor "$DOTFILES_DIR/zed/settings.json" "$ZED_USER_DIR/settings.json"
        [ -f "$DOTFILES_DIR/zed/keymap.json" ] && link_editor "$DOTFILES_DIR/zed/keymap.json" "$ZED_USER_DIR/keymap.json"
        # Zed uses its own snippet format (snippets/*.json), so the VS Code
        # .code-snippets files are not linked here.
    else
        echo "⚠️  No zed/ config in this repo. Skipping links."
    fi
elif [ -d "$VSCODE_USER_DIR" ]; then
    [ -f "$DOTFILES_DIR/vscode/settings.json" ] && link_editor "$DOTFILES_DIR/vscode/settings.json" "$VSCODE_USER_DIR/settings.json"
    [ -d "$DOTFILES_DIR/vscode/snippets" ] && link_editor "$DOTFILES_DIR/vscode/snippets" "$VSCODE_USER_DIR/snippets"
else
    echo "⚠️  VS Code user directory not found. Skipping links."
fi

echo "✨ Done! Restart Git Bash."
